version: "3"
services:
  backend_graphql:
    image: "node:14"
    entrypoint:
      - "sh"
      - "-c"
      - "npm install && npm start"
    working_dir: "/usr/src/app"
    ports:
      - "3000:3000"
    volumes:
      - "./backend/graphql_api/lambda:/usr/src/app"
      # Don't sync the node_modules directory back to the client.
      - "/usr/src/app/node_modules"
    depends_on:
      - backend_pg
    links:
      - "backend_pg:gov-agenda-notifier_backend_pg_1"
    networks:
      - my_network
  backend_pg:
    build: "./backend/docker_for_local_dev_db"
    # this is for debugging; graphql connects to PG via internal docker network
    ports:
      - "5431:5432"
    volumes:
      - ./backend/docker_for_local_dev_db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my_network
  backend_upload:
    image: "node:14"
    entrypoint:
      - "sh"
      - "-c"
      - "npm install && npm start"
    working_dir: "/usr/src/app"
    ports:
      - "3002:3002"
    volumes:
      - "./backend/agenda_upload_service/lambda:/usr/src/app"
      # Don't sync the node_modules directory back to the client.
      - "/usr/src/app/node_modules"
    depends_on:
      - backend_pg
      - frontend
    links:
      - "backend_pg:gov-agenda-notifier_backend_pg_1"
    networks:
      - my_network
  frontend:
    # node-sass 4* needs node version 14
    image: "node:14"
    entrypoint:
      - "sh"
      - "-c"
      - "npm install && npm start"
    working_dir: "/usr/src/app"
    ports:
      - "3001:3000"
    volumes:
      - "./frontend:/usr/src/app"
      # Don't sync the node_modules directory back to the client.
      - "/usr/src/app/node_modules"
    stdin_open: true
    depends_on:
      - backend_pg
    environment:
      - REACT_APP_GRAPHQL_URL=http://localhost:3000
      - REACT_APP_JWT_ISSUER=ADD-ISSUER-DOMAIN
    links:
      - "backend_pg:gov-agenda-notifier_backend_pg_1"
    networks:
      - my_network
volumes:
  postgres-data:
networks:
  my_network:
    name: my_network
    driver: bridge
